apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-job
  namespace: simple-social
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: simple-social
      containers:
        - name: db-migrate
          image: simple-social:latest
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: simple-social-secrets
            - configMapRef:
                name: simple-social-config