apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: simple-social-secrets
  namespace: simple-social
spec:
  refreshInterval: 1h
  target:
    name: simple-social-secrets
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: arn:aws:ssm:us-east-1:992646609003:parameter/simple_social/dev/rds/db_name
      sourceRef:
        storeRef:
          name: simple-social-ssm
          kind: SecretStore
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:992646609003:secret:rds!db-def56d12-9721-4fb7-a47a-f6cc245a8f86-jHufkn
      sourceRef:
        storeRef:
          name: simple-social-secret-manager
          kind: SecretStore
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: arn:aws:ssm:us-east-1:992646609003:parameter/simple_social/dev/rds/db_host
      sourceRef:
        storeRef:
          name: simple-social-ssm
          kind: SecretStore
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: arn:aws:ssm:us-east-1:992646609003:parameter/simple_social/dev/rds/db_port
      sourceRef:
        storeRef:
          name: simple-social-ssm
          kind: SecretStore

  dataFrom:
    - sourceRef:
        storeRef:
          name: simple-social-secret-manager
          kind: SecretStore
      extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: arn:aws:secretsmanager:us-east-1:992646609003:secret:/simple-social/dev-0LaQJG
        metadataPolicy: None