apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: simple-social-secret-manager
  namespace: simple-social

spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1