apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-social
  namespace: simple-social
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP