apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - external-secrets-store-ssm.yaml
  - external-secrets.yaml
  - configmap.yaml
  - external-secrets-store-sm.yaml
  - servicemonitor.yaml
patches:
  - path: ingress-patch.yaml
images:
  - name: simple-social
    newName: 992646609003.dkr.ecr.us-east-1.amazonaws.com/gitops-infra-terraform-ecr
    newTag: sha-fb39ee1
