name: Build, scan and push 
on:
  push:
    branches:
      - main
    paths-ignore: 
      - .github/**
      - k8s/**
 
permissions:
  id-token: write  
  contents: write
  pull-requests: write
  security-events: write


jobs:
  build-scan-push:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: code
    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.image-tag }}
      image-name: ${{ steps.set-image-name.outputs.image-name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c

      - name: set short SHA
        id: set-image-tag
        run: echo "image-tag=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64
      
      - name: build image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: code
          load: true
          tags: ${{ env.REGISTRY }}/${{ vars.ECR_REPO_NAME }}:${{ steps.set-image-tag.outputs.image-tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: trivy scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          image-ref: ${{ env.REGISTRY }}/${{ vars.ECR_REPO_NAME }}:${{ steps.set-image-tag.outputs.image-tag }}
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          trivyignores: ${{ github.workspace }}/code/.trivyignore
      
      - name: push image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag ${{ env.REGISTRY }}/${{ vars.ECR_REPO_NAME }}:${{ steps.set-image-tag.outputs.image-tag }} ${{ env.REGISTRY }}/${{ vars.ECR_REPO_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ vars.ECR_REPO_NAME }}:${{ steps.set-image-tag.outputs.image-tag }}
          docker push ${{ env.REGISTRY }}/${{ vars.ECR_REPO_NAME }}:latest
      - name: set image name
        id: set-image-name
        run: echo "image-name=${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPO_NAME }}" >> $GITHUB_OUTPUT

  open-pr:
    needs: build-scan-push
    runs-on: ubuntu-24.04
    outputs:
      updated-kustomization: ${{ steps.bump-image-tag.outputs.updated-kustomization }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name:  Bump image tag in kustomization.yaml
        env:
          IMAGE_TAG: ${{ needs.build-scan-push.outputs.image-tag }}
          IMAGE_NAME: ${{ needs.build-scan-push.outputs.image-name }}
        uses: mikefarah/yq@1b9b4ac5187171d2e5e3129be0cfa827c7f9d53d
        with:
          cmd: yq -i '(.images[] | select(.name == "simple-social")) .newName = strenv(IMAGE_NAME) | (.images[] | select(.name == "simple-social")) .newTag = strenv(IMAGE_TAG)' k8s/overlays/dev/kustomization.yaml


      - name: output updated kustomization.yaml
        id: bump-image-tag
        run: echo "updated-kustomization=$(cat k8s/overlays/dev/kustomization.yaml)" >> $GITHUB_OUTPUT
      - name: Commit and open PR
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump image tag to ${{ needs.build-scan-push.outputs.image-tag }}\n\nUpdated kustomization file ${{ steps.bump-image-tag.outputs.updated-kustomization }}"
          title: "Bump image tag to ${{ needs.build-scan-push.outputs.image-tag }}"
          body: "This PR bumps the image tag to ${{ needs.build-scan-push.outputs.image-tag }}. Updated kustomization.yaml is attached."
          branch: bump-image-tag-{{ needs.build-scan-push.outputs.image-tag }}
